// 常量定义
export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'
export const ADD_NUMBER = 'ADD_NUMBER'
export const SUB_NUMBER = 'SUB_NUMBER'

export const GET_BANNAERDATA = 'GET_BANNAERDATA'
export const GET_RECOMMENDATA = 'GET_RECOMMENDATA'

export const FETCH_HOME_MULTIDATA = 'FETCH_HOME_MULTIDATA'
