import ReactDOM from 'react-dom'

// import App from './01-组件的定义方式/01-组件的定义'
// import App from './01-组件的定义方式/02-render-返回值'
// import App from './02-组件的生命周期/App'
// import App from './03-组件间的通信/01-组件之间的嵌套'
// import App from './03-组件间的通信/02-父传子通信-类组件'
// import App from './03-组件间的通信/03-父传子通信-函数组件'
// import App from './03-组件间的通信/04-父传子通信-属性验证'
// import App from './03-组件间的通信/05-子传父通信-函数组件-函数传递'
// import App from './04-组件通信案例/App'
// import App from './05-React方式来实现slot-插槽/App'
// import App from './06-跨组件通信/01-props-层层传递'
// import App from './06-跨组件通信/02-context-共享'
// import App from './06-跨组件通信/03-context-函数组件'
// import App from './06-跨组件通信/04-context-多个context'
// import App from './07-setState详解/01-为什么要使用setState'
// import App from './07-setState详解/02-setState-异步更新'
// import App from './07-setState详解/03-setState-数据的合并-assign'
// import App from './08-性能优化/01-组件嵌套的render调用'
// import App from './08-性能优化/02-通过-shouldComponentUpdate-阻断render'
// import App from './08-性能优化/03-函数组件优化-memo'
// import App from './09-知识补充/01-事件总线'
// import App from './09-知识补充/02-refs-使用'
// import App from './09-知识补充/03-如何在函数组件中使用ref'
// import App from './09-知识补充/04-portals-使用'
import App from './09-知识补充/05-fragment-使用'
// import App from './10-受控组件和非受控组件/01-受控组件的基本演练'
// import App from './10-受控组件和非受控组件/02-受控组件-selected'
// import App from './10-受控组件和非受控组件/03-受控组件-多输入'
// import App from './10-受控组件和非受控组件/04-非受控组件'
// import App from './11-高阶组件/01-高阶组件的定义'
// import App from './11-高阶组件/02-高阶组件-props增强'
// import App from './11-高阶组件/03-高阶组件混合-context-演练'
// import App from './11-高阶组件/04-高阶组件-生命周期劫持'

ReactDOM.render(<App />, document.querySelector('#root'))
